# Generated by Django 4.1.2 on 2022-11-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='sqft',
        ),
    ]
