# Generated by Django 4.1.2 on 2023-02-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_remove_listing_sqft'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='open_house',
            field=models.BooleanField(default=False),
        ),
    ]
